apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: helderprado/tcc-escalabilidade:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000

          command: ["uvicorn", "app.api.main:app", "--workers", "2", "--host", "0.0.0.0", "--port", "8000"]

          envFrom:
            - secretRef:
                name: tcc-escalabilidade-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080