apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
spec:
  replicas: 5
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
        - name: celery
          image: helderprado/tcc-escalabilidade:1.0.0
          imagePullPolicy: Always
          command: ["celery", "-A", "app.celery.worker.celery", "worker", "-l", "info", "--concurrency=4", "--prefetch-multiplier=2"]
          envFrom:
            - secretRef:
                name: tcc-escalabilidade-secrets