apiVersion: v1
kind: Secret
metadata:
  name: tcc-escalabilidade-secrets
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_DB: ZGI=
  DATABASE_URL: cG9zdGdyZXNxbCtwc3ljb3BnMjovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzLXNlcnZpY2UuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbC9kYg==
  RABBITMQ_HOST: cmFiYml0bXE=
  RABBITMQ_PORT: NTY3Mg==
  CELERY_BROKER_URL: YW1xcDovL2d1ZXN0Omd1ZXN0QHJhYmJpdG1xLXNlcnZpY2UuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbA==
  CELERY_BACKEND_URL: cmVkaXM6Ly9yZWRpcy1zZXJ2aWNlLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6NjM3OS8w