apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust
  template:
    metadata:
      labels:
        app: locust
    spec:
      containers:
      - name: locust
        image: helderprado/tcc-locust:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8089
        command: ["locust", "-f", "stress_test_case_1.py", "--host", "http://api-service.default.svc.cluster.local:8000"]
---
apiVersion: v1
kind: Service
metadata:
  name: locust-service
spec:
  selector:
    app: locust
  ports:
    - protocol: TCP
      port: 8089  
      targetPort: 8089  
      nodePort: 30000  
  type: NodePort
